name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-18"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWM5Mzc3NWUtYzM1Mi00MWE5LWIxNzUtZGJlMTFiZTdjN2FjIiwidGVuYW50X2lkIjoiMGZlYWJhYWRlYzYyNGM2YTFiZWI3ZTEwMzA3ZDNmY2M0NzNlZTZlOGI5MmY5YjQxYjcwOWVjOTkwZmZjNTRmYSIsImludGVybmFsX3NlY3JldCI6IjQ3YTU2OGQ0LTczNDktNDVmZi05NmQ2LWIwNWJmYTQ2MmU4MSJ9.xZlsl7NwpO8yJxooNYxbyXaCGuNpWD7m4rGE_L1gCes"
